name = "myjulia"
uuid = "df063513-a479-4e5f-8871-6bebbb7c56a9"
authors = ["Jeff Lynch <jjlynch@osteocoder.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
